FROM databricksruntime/runtime:9.3.x-scala2.12

# Instalar bibliotecas adicionais
RUN pip install pandas numpy scikit-learn

# Copiar notebooks e scripts (Se utilizar o Jupter)
# COPY components/notebooks/ ./notebooks/
# COPY components/scripts/ ./scripts/

# Comando para iniciar o notebook
# CMD ["jupyter", "notebook", "--allow-root"]
